networks:
  lan_a:
    ipam:
      config:
        - subnet: 172.32.0.0/24

services:
  citynet:
    hostname: citynet
    build: 
      context: ./site/cityNet/
    restart: always
    networks:
      lan_a:
        ipv4_address: 172.32.0.7

  console:
    hostname: console
    build: 
      context: ./console/
    restart: always
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "22:22"
    networks:
      lan_a:
        ipv4_address: 172.32.0.8
