#!/bin/zsh

KEY_FILE="./challenge-1/.flag"

check_key() {
    echo "Connecting to CityNet Monitoring System, Dawson District..."
    echo "Please enter the key:"
    read input_key  # Read the input key silently

    # Read the key from the file
    file_key=$(cat "$KEY_FILE")

    # Compare the input key with the key from the file
    if [[ "$input_key" == "$file_key" ]]; then
        echo "Access granted. Logging in..."
        tmux resize-pane -Z
        sshpass -p 'passwd' ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null cityadmin@172.32.0.7
    else
        echo "Access denied. Incorrect key."
    fi
}

# Main script execution
while true;
do
    clear
    check_key
done
